			<div class="grid_wrapper">

				<div class="g_6 contents_header">
					<h3 class="i_16_dashboard tab_label">Dashboard</h3>
					<div><span class="label">Ogólne informacje.</span></div>
				</div>
				<div class="g_6 contents_options">
					<!-- 
					<div class="simple_buttons">
						<div class="bwIcon i_16_help">Help</div>
					</div>
					<div class="simple_buttons">
						<div class="bwIcon i_16_settings">Settings</div>
						<div class="buttons_arrow">
						</div>
					</div> -->
				</div>

				<div class="g_12 separator"><span></span></div>

				<!-- Quick Statistics -->
				<div class="g_3 quick_stats">
					<div class="big_stats visitor_stats">
						<?php echo $this->newsletter['num']; ?>
					</div>
					<h5 class="stats_info">Emaili w newsletter</h5>
				</div>
				<div class="g_3 quick_stats">
					<div class="big_stats users_stats">
						<?php echo $this->user['num']; ?>
					</div>
					<h5 class="stats_info">Użytkowników</h5>
				</div>
				<div class="g_3 quick_stats">
					<div class="big_stats orders_stats">
						<?php echo $this->news['num']; ?>
					</div>
					<h5 class="stats_info">Aktualnosci</h5>
				</div>
				<div class="g_3 quick_stats">
					<div class="big_stats tickets_stats">
						<?php echo $this->offer['num']; ?>
					</div>
					<h5 class="stats_info">Ofert</h5>
				</div>

				<div class="g_12 separator under_stat"><span></span></div>

				<!-- Charts -->
				<div class="g_12">
					<div>Statystyki odwiedzin - w przyszłosci.</div>


				</div>
				<!-- Separator -->
				<div class="g_12 separator"><span></span></div>
				<!-- Chats -->



			</div>
