<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/> 
	 <?php echo $this->headTitle(); ?>
	<!--[if lt IE 9]>
		<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	
	<!-- The Main CSS File -->
	
	
	<?php 
	$this->headLink()->prependStylesheet($this->baseUrl().'/page/css/style_slider.css'); 
	$this->headLink()->prependStylesheet($this->baseUrl().'/page/css/formcss.css');
	$this->headLink()->prependStylesheet($this->baseUrl().'/page/css/tiptip.css');
	echo $this->headLink()->prependStylesheet($this->baseUrl().'/page/css/style.css');
    echo $this->jQuery()->setCdnSsl(true)->setVersion('1.7')->enable()->setUiLocalPath('https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js')->UIenable();
    $this->headScript()->appendFile($this->baseUrl().'/page/js/scripts.js');
	$this->headScript()->appendFile($this->baseUrl().'/page/js/jquery.scrollintoView.min.js');
	$this->headScript()->appendFile($this->baseUrl().'/page/js/jquery.jfontsize-1.0.js');
	$this->headScript()->appendFile($this->baseUrl().'/page/js/jquery.tiptip.minified.js');
    echo $this->headScript()->appendFile($this->baseUrl().'/page/js/jquery.uniform.js'); 
    ?>
	 
	 <script type="text/javascript">
				$(document).ready(function() {
        			//$('br').remove();
					$(function(){
						$("#apply_form input,#apply_form textarea,#apply_form select,#apply_form button").uniform();
						$("#contact_form input,#contact_form textarea,#contact_form select,#contact_form button").uniform();
						$("#form_agent input,#form_agent textarea,#form_agent select,#form_agent button").uniform();				
					});
				});
	</script>				
	<script type="text/javascript">
			$(document).ready(function() {
    			$(function(){
    				$(".table_body_left .newsletter_bottom").tipTip({maxWidth: "auto", edgeOffset: 10});
    			});
			});
	</script>	
	
</head>
<body>
                <?php 				
				function getPercent2($first_value,$second_value){
				    $wynik =  (($second_value/$first_value)*100)-100;
				    $wynik = round($wynik,'2');
				    return $wynik;
				}
				?>


	<div id="page">
			
		<div id="contener">
			<div class="menu">
				<div class="menu_center">
    				<?php include 'menu.phtml'?>
				</div>
			</div>
			<div id="head">
				<div class="logos">
					<div class="logo">
						<a href="/"><img  src="<?php echo $this->baseUrl(); ?>/page/css/image/logo.png" alt="<i18n>bzk.logo</i18n>" /></a>
				</div>
				
				<div class="partner">
						<a target="_blank" href="http://www.bakoma.pl/pl/"><img src="<?php echo $this->baseUrl(); ?>/page/css/image/bacoma.png" alt="<i18n>bacoma.logo</i18n>" class="to_left" /></a>
						<a target="_blank" href="http://www.bioagra-oil.pl/"><img src="<?php echo $this->baseUrl(); ?>/page/css/image/bioagra-oil.png" alt="<i18n>bioagraoil.logo</i18n>" class="to_left" /></a>
						<a target="_blank" href="http://www.bioagra.pl/"><img src="<?php echo $this->baseUrl(); ?>/page/css/image/bioagra.png" alt="<i18n>bioagra.logo</i18n>" class="to_left" /></a>
						<a target="_blank" href="http://www.komagra.pl/"><img src="<?php echo $this->baseUrl(); ?>/page/css/image/komagra.png" alt="<i18n>komagra.logo</i18n>" class="to_left" /></a>
						<a target="_blank" href="http://www.polskiemlyny.pl"><img src="<?php echo $this->baseUrl(); ?>/page/css/image/mlyny.png" alt="<i18n>mlyny.logo</i18n>" class="to_left" /> </a>
				</div>
				
				</div>
				
				
				
				  <div id="header">
  					
				</div>				
					
				
				<!--<div class="notowania">
					<marquee>
						<?php 
						    foreach($this->layout()->marquee as $aMarquee):
						        $percent = getPercent2($aMarquee['close'],$aMarquee['close_last']);
						        $img = '';
						        if($percent > 0){
						            $img = '<img src="'.$this->baseUrl().'/page/css/image/arrow_up.png"/>';
						        }elseif($percent < 0){
						            $img = '<img src="'.$this->baseUrl().'/page/css/image/arrow_down.png"/>';
						        }
                                echo $aMarquee['name'].' | '.$img.' '.$aMarquee['close'].' | '.$percent.'% | '.$aMarquee['date'].' ';
						    endforeach;
						?>
						</marquee>						
				</div>-->
				<div id="body">
				<div class="where"> <i18n>you.are.here</i18n>: 
					<?php 
      					  $count_bread = count($this->layout()->breadcrumb);
       						 $count = 0;
          			          foreach($this->layout()->breadcrumb as $breadcrumb):
           			             echo '<b>'. $breadcrumb .'</b>';
             		           $count++;
              		          if($count != $count_bread){
              		              echo ' <img src="'.$this->baseUrl().'/page/css/image/arrow_place.png" />';
               			         }
             			       endforeach;
                    ?>
				</div>

					<?php echo $this->layout()->content; ?>

				</div>
				
			<?php include 'footer.phtml';?>
			</div>
			
		</div>
		</div>		
</body>
</html>