<div class="column_left">
					<div class="shadow_top"></div>
					<div class="sub_menu">
						<h2>SKORZYSTAJ Z SUBMENU</h2>
						<ul>
							<?php foreach($this->menu as $key => $value):
                                echo '<li><a href='.$this->url(array('controller'=>'show','action'=>'jobspage','id'=>$value['id'])).'>'.$value['title'].'</a></li>';
							    endforeach;
							?>
							
						</ul>
					</div>
					<div class="shadow_bot"></div>
					
</div>
<div class="column_center">
<div class="main_content">
<?php
if(!empty($this->page)):
    echo '<ul>';
    foreach($this->page as $key => $value):
        echo '<li><a href='.$this->url(array('controller'=>'page','action'=>'index','name'=>$value['name_link'])).'>'.$value['title'].'</li>';
    endforeach;
    echo '</ul>';
endif;
?>
<?php
if(!empty($this->content)):
    echo '<ul>';
    foreach($this->content as $key => $value):
        echo '<li><a href='.$this->url(array('controller'=>'show','action'=>'contentpage','id'=>$value['id'])).'>'.$value['title'].'</li>';
    endforeach;
    echo '</ul>';
endif;
?>
</div>
</div>